export type EmailTemplate = {
  id: string;
  name: string;
  category: string;
  description: string;
  html: string;
};

const shell = (accent: string, inner: string) => `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f7;padding:24px 12px;font-family:Arial,sans-serif"><tr><td align="center"><table role="presentation" width="100%" style="max-width:600px;background:#fff;border-radius:16px;overflow:hidden"><tr><td>${inner}</td></tr></table></td></tr></table>`;

export const EMAIL_TEMPLATES: EmailTemplate[] = [
 {id:"launch",name:"Product Launch",category:"Marketing",description:"Hero image, launch message and CTA.",html:shell("#6a53f6",'<img src="https://placehold.co/600x280/png?text=YOUR+HERO+IMAGE" width="600" style="display:block;width:100%;height:auto"><div style="padding:32px"><p style="color:#6a53f6;font-size:12px;font-weight:bold">NEW FROM YOUR BRAND</p><h1 style="font-size:32px;color:#171722">Something worth opening.</h1><p style="font-size:16px;line-height:1.6;color:#666">Introduce your product, offer or big announcement with a clear message.</p><a href="https://example.com" style="display:inline-block;background:#6a53f6;color:#fff;padding:14px 22px;border-radius:9px;text-decoration:none;font-weight:bold">Explore Now</a></div>')},
 {id:"newsletter",name:"Weekly Newsletter",category:"Newsletter",description:"Editorial layout for updates, links and stories.",html:shell("#6a53f6",'<div style="padding:30px"><strong style="font-size:20px">YOUR BRAND</strong><p style="color:#6a53f6;font-size:12px;font-weight:bold;margin-top:28px">THIS WEEK</p><h1 style="font-size:28px">What you need to know.</h1><p style="font-size:15px;line-height:1.6;color:#666">A concise introduction to your latest updates.</p><hr style="border:0;border-top:1px solid #eee"><h2 style="font-size:19px">01 — Main story</h2><p style="color:#666;line-height:1.6">Write your story here and add a link.</p><a href="https://example.com" style="color:#6a53f6;font-weight:bold">Read more →</a></div>')},
 {id:"promo",name:"Offer / Promotion",category:"Sales",description:"High-impact promotional email with a focused offer.",html:shell("#e47b21",'<div style="padding:38px 30px;text-align:center;background:#fff0e4"><p style="color:#e47b21;font-weight:bold">LIMITED-TIME OFFER</p><h1 style="font-size:40px">SAVE 30%</h1><p style="font-size:16px;line-height:1.6;color:#555">Give customers a reason to act now.</p><img src="https://placehold.co/540x220/png?text=YOUR+PRODUCT" width="540" style="width:100%;height:auto;border-radius:12px"><a href="https://example.com" style="display:inline-block;background:#e47b21;color:#fff;padding:15px 28px;border-radius:9px;text-decoration:none;font-weight:bold;margin-top:20px">Claim the Offer</a></div>')},
 {id:"event",name:"Event Invitation",category:"Events",description:"Date, venue and RSVP-focused invitation.",html:'<table role="presentation" width="100%" style="background:#0d1b3d;color:#fff"><tr><td style="padding:38px 32px"><p style="color:#f26d21;font-weight:bold">YOU’RE INVITED</p><h1 style="font-size:34px">Your Event Name</h1><p style="line-height:1.6;color:#dfe4f2">Bring your audience together for an experience they will remember.</p><div style="background:#1b2b51;padding:16px;margin:20px 0">DATE<br><span style="color:#cfd6e6">Saturday, 24 October 2026</span></div><div style="background:#1b2b51;padding:16px;margin-bottom:20px">VENUE<br><span style="color:#cfd6e6">Your Venue, Lagos</span></div><a href="https://example.com" style="background:#f26d21;color:#fff;padding:14px 22px;border-radius:9px;text-decoration:none;font-weight:bold">Reserve My Seat</a></td></tr></table>'},
 {id:"welcome",name:"Welcome Email",category:"Lifecycle",description:"Warm onboarding email for new subscribers.",html:shell("#6a53f6",'<div style="padding:36px 32px"><div style="font-size:30px">👋</div><h1 style="font-size:30px">Welcome to the family.</h1><p style="font-size:15px;line-height:1.7;color:#666">Thanks for joining us. Tell subscribers what they can expect and give them their first useful next step.</p><a href="https://example.com" style="display:inline-block;background:#6a53f6;color:#fff;padding:14px 22px;border-radius:9px;text-decoration:none;font-weight:bold">Get Started</a></div>')},
 {id:"story",name:"Story / Editorial",category:"Content",description:"Image-led storytelling for brands and creators.",html:shell("#a06a35",'<img src="https://placehold.co/600x330/png?text=STORY+IMAGE" width="600" style="display:block;width:100%;height:auto"><div style="padding:34px"><p style="color:#a06a35;font-size:11px;font-weight:bold">THE STORY</p><h1 style="font-family:Georgia,serif;font-size:34px">A story people want to finish.</h1><p style="font-family:Georgia,serif;font-size:17px;line-height:1.8;color:#5f5a50">Use this layout for founder stories, customer stories and thought leadership.</p><a href="https://example.com" style="color:#a06a35;font-weight:bold">Continue reading →</a></div>')},
 {id:"product",name:"Product Showcase",category:"Commerce",description:"Product image, benefits, price and purchase CTA.",html:shell("#171722",'<div style="padding:26px;text-align:center"><img src="https://placehold.co/520x420/png?text=PRODUCT+PHOTO" width="520" style="width:100%;max-width:520px;height:auto;border-radius:14px"><h1 style="font-size:27px">Your Product Name</h1><p style="color:#777;line-height:1.6">A short product description focused on the customer benefit.</p><p style="font-size:24px;font-weight:bold">₦XX,XXX</p><a href="https://example.com" style="display:inline-block;background:#171722;color:#fff;padding:14px 24px;border-radius:9px;text-decoration:none;font-weight:bold">Shop Now</a></div>')},
 {id:"announcement",name:"Big Announcement",category:"Announcements",description:"Minimal high-contrast announcement.",html:'<table role="presentation" width="100%" style="background:#6a53f6;color:#fff"><tr><td style="padding:60px 30px;text-align:center"><p style="font-size:12px;font-weight:bold">BIG NEWS</p><h1 style="font-size:42px">We have something to tell you.</h1><p style="line-height:1.7;color:#eeeaff">Explain what changed, why it matters and what readers should do next.</p><a href="https://example.com" style="display:inline-block;background:#fff;color:#5940ff;padding:14px 22px;border-radius:9px;text-decoration:none;font-weight:bold">See What’s New</a></td></tr></table>'},
 {id:"thankyou",name:"Thank You",category:"Relationship",description:"Appreciation email for customers and communities.",html:shell("#a34d2e",'<div style="padding:45px 30px;text-align:center"><div style="font-size:40px">❤️</div><h1 style="font-size:32px">Thank you.</h1><p style="font-size:16px;line-height:1.7;color:#6c625c">Share a genuine note from your team and make your audience feel appreciated.</p><img src="https://placehold.co/540x220/png?text=YOUR+BRAND+PHOTO" width="540" style="width:100%;height:auto;border-radius:12px"><a href="https://example.com" style="color:#a34d2e;font-weight:bold;text-decoration:none">Visit us →</a></div>')},
 {id:"video",name:"Video Campaign",category:"Rich Media",description:"Clickable video thumbnail designed for email clients.",html:shell("#6a53f6",'<a href="https://example.com/video"><img src="https://placehold.co/600x340/png?text=%E2%96%B6+WATCH+VIDEO" width="600" style="display:block;width:100%;height:auto"></a><div style="padding:30px"><p style="color:#6a53f6;font-size:12px;font-weight:bold">WATCH NOW</p><h1 style="font-size:28px">Your video deserves an email.</h1><p style="color:#666;line-height:1.6">The thumbnail links to the video, which works more reliably across email clients than embedded HTML5 video.</p><a href="https://example.com/video" style="display:inline-block;background:#6a53f6;color:#fff;padding:14px 22px;border-radius:9px;text-decoration:none;font-weight:bold">Watch Video</a></div>')}
];