"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Mail, Save, Send, ShieldCheck, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { getOrCreateWorkspace } from "@/lib/inbux/workspace";

export default function CampaignsPage(){
 const supabase=createClient();
 const [id,setId]=useState(""),[campaign,setCampaign]=useState<any>(null),[contacts,setContacts]=useState<any[]>([]),[workspace,setWorkspace]=useState<any>(null);
 const [subject,setSubject]=useState(""),[preview,setPreview]=useState(""),[fromName,setFromName]=useState(""),[fromEmail,setFromEmail]=useState(""),[replyTo,setReplyTo]=useState(""),[body,setBody]=useState(""),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");
 useEffect(()=>{setId(new URLSearchParams(location.search).get("id")||"")},[]);
 useEffect(()=>{if(!id)return;(async()=>{const ws=await getOrCreateWorkspace(supabase);if(!ws)return;setWorkspace(ws);const [{data:c},{data:p}]=await Promise.all([supabase.from("campaigns").select("*").eq("id",id).eq("workspace_id",ws.id).single(),supabase.from("contacts").select("id,email,status").eq("workspace_id",ws.id).eq("status","subscribed")]);if(c){setCampaign(c);setSubject(c.subject||"");setPreview(c.preview_text||"");setFromName(c.from_name||ws.name||"");setFromEmail(c.from_email||"");setReplyTo(c.reply_to||"");setBody(c.html_content||"")}setContacts(p||[])})()},[id]);
 const missing=[] as string[];if(!subject.trim())missing.push("Subject");if(!fromName.trim())missing.push("From name");if(!fromEmail.trim())missing.push("From email");if(!body.trim())missing.push("Content");if(!contacts.length)missing.push("Audience");
 async function save(){if(!campaign||!workspace)return;setSaving(true);const {error:e}=await supabase.from("campaigns").update({subject:subject||null,preview_text:preview||null,from_name:fromName||null,from_email:fromEmail||null,reply_to:replyTo||null,html_content:body,audience_count:contacts.length,updated_at:new Date().toISOString()}).eq("id",campaign.id).eq("workspace_id",workspace.id);setSaving(false);if(e)setError(e.message);else{setSaved(true);setTimeout(()=>setSaved(false),1500)}}
 if(!campaign)return <main className="campaign-editor"><div className="empty"><strong>{id?"Loading campaign…":"No campaign selected"}</strong></div></main>;
 return <main className="campaign-editor"><header className="editor-head"><div><button className="back-link" onClick={()=>location.assign("/")}>← Dashboard</button><div className="eyebrow">CAMPAIGN DRAFT</div><h1>{campaign.name}</h1><p>Build your email and run a safety check before sending.</p></div><div className="editor-actions"><button className="ghost-btn" onClick={save}><Save size={14}/>{saving?"Saving…":"Save draft"}</button><button className="primary" onClick={()=>setError(missing.length?"Complete: "+missing.join(", "):"Preflight passed. Sending remains locked until a verified provider and domain are configured.")}><Send size={14}/> Preflight</button></div></header><div className="editor-layout"><section className="editor-main"><div className="panel editor-card"><div className="editor-section-title"><Mail size={16}/><div><strong>Message</strong><span>What subscribers receive</span></div></div><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Your subject line"/></label><label>Preview text<input value={preview} onChange={e=>setPreview(e.target.value)} placeholder="Inbox preview text"/></label><label>Email content<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Write your email…"/></label></div><div className="panel editor-card"><div className="editor-section-title"><Send size={16}/><div><strong>Sender</strong><span>Authenticated sending identity</span></div></div><div className="two-fields"><label>From name<input value={fromName} onChange={e=>setFromName(e.target.value)} placeholder="Your brand"/></label><label>From email<input value={fromEmail} onChange={e=>setFromEmail(e.target.value)} placeholder="hello@yourdomain.com"/></label></div><label>Reply-to<input value={replyTo} onChange={e=>setReplyTo(e.target.value)} placeholder="reply@yourdomain.com"/></label></div></section><aside className="editor-side"><div className="panel editor-card"><div className="editor-section-title"><Users size={16}/><div><strong>Audience</strong><span>Protected subscribers</span></div></div><div className="audience-number">{contacts.length.toLocaleString()}</div><p className="side-copy">Suppressed and unsubscribed contacts are excluded.</p><button className="text-btn" onClick={()=>location.assign("/contacts")}>Manage contacts</button></div><div className="panel editor-card"><div className="editor-section-title"><ShieldCheck size={16}/><div><strong>Preflight</strong><span>Before any send</span></div></div>{missing.length?<div className="check-list">{missing.map(x=><div className="check-item" key={x}><span>!</span>{x}</div>)}</div>:<div className="check-ok"><CheckCircle2 size={16}/> Ready for preflight</div>}<div className="editor-lock">Real sending is locked until a verified sending domain and provider credentials are configured.</div></div></aside></div>{saved&&<div className="save-toast"><CheckCircle2 size={15}/> Draft saved</div>}{error&&<div className="error-toast">{error}</div>}</main>;
}